# Generated by Django 4.0.1 on 2022-01-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='Answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.activitymodel')),
            ],
        ),
    ]
