# Generated by Django 4.0.1 on 2022-01-10 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_propertymodel_options_propertymodel_id_and_more'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymodel',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertymodel', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='status',
            field=models.CharField(choices=[('DISABLED', 'disabled'), ('ACTIVE', 'active'), ('CANCELLED', 'cancelled'), ('DONE', 'done')], default='ACTIVE', max_length=255),
        ),
    ]
