# Generated by Django 4.0.1 on 2022-01-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('disabled_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
