# Generated by Django 4.0.1 on 2022-01-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertymodel',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='status',
            field=models.CharField(choices=[('DISABLED', 'disabled'), ('ENABLED', 'enabled')], default='ENABLED', max_length=255),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
